import { prisma } from '../../lib/prisma';
import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
import { analyticsService } from '../analytics/analytics.service';
import { buildReportHTML } from './templates/report.template';
import { env } from '../../config/env';
import logger from '../../lib/logger';

export class ReportsService {
  async generatePDFReport(repoId: string, userId: string): Promise<Buffer> {
    const repo = await prisma.repository.findFirst({
      where: { id: repoId, userId },
      include: {
        healthScore: true,
        aiInsights: {
          orderBy: { generatedAt: 'desc' },
          take: 3
        }
      }
    });

    if (!repo) throw new Error('Repository not found or access denied');

    const [
      overview,
      commits,
      contributors,
      prs,
      issues,
      cicd
    ] = await Promise.all([
      analyticsService.getOverview(repoId),
      analyticsService.getCommits(repoId, '30d'),
      analyticsService.getContributors(repoId),
      analyticsService.getPullRequests(repoId, '30d'),
      analyticsService.getIssues(repoId, '30d'),
      analyticsService.getCicd(repoId, '30d')
    ]);

    const data = {
      repo,
      overview,
      commits,
      contributors: contributors.contributors.slice(0, 5),
      prs,
      issues,
      cicd,
      healthScore: repo.healthScore,
      aiInsights: repo.aiInsights
    };

    const html = buildReportHTML(data);

    let browser;
    try {
      const executablePath = env.PUPPETEER_EXECUTABLE_PATH || await chromium.executablePath();
      
      browser = await puppeteer.launch({
        executablePath,
        args: chromium.args,
        headless: true,
      });

      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'load' });

      const pdf = await page.pdf({        format: 'A4',
        printBackground: true,
        margin: { top: '24mm', bottom: '24mm', left: '16mm', right: '16mm' },
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="width: 100%; font-size: 10px; font-family: system-ui, sans-serif; color: #6b7280; padding: 0 16mm; display: flex; justify-content: space-between;">
            <span>Generated by Commitra &middot; commitra.app &middot; ${new Date().toLocaleDateString()}</span>
            <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `
      });

      return Buffer.from(pdf);
    } catch (error: any) {
      logger.error({ repoId, error: error.message }, 'Failed to generate PDF report');
      throw new Error('PDF generation failed');
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }
}

export const reportsService = new ReportsService();
export default reportsService;
